version: '3.7'

services:
 treedbserver:
  image: mariadb:10.3.32-focal
  container_name: tree_dbserver
  volumes:
  - ./dbdata:/var/lib/mysql
  - ./sqlinit:/docker-entrypoint-initdb.d/
  ports:
  - "3306:3306"
  environment:
   TZ: Europe/Berlin
   MYSQL_ROOT_PASSWORD: admin 
  
 treeappserver:
  build:
   context: ./
   dockerfile: appserver.dockerfile
  image: treeappserver:lastest
  container_name: tree_appserver
  volumes:
  - ./autodeploy:/opt/payara/appserver/glassfish/domains/domain1/autodeploy
  ports:
  - "8080:8080"
  - "4848:4848"
  - "9009:9009"
  environment:
   PINGMSG: "Got Ping-Request at: "
  
